export const ProductsData = [
  {
    id: 0,
    link: "https://backend.partsg.com/storage/528/conversions/piplines-(1)-thumb.jpg",
    name: "Pipes",
    model: "12135",
    price: "5,745",
    stock: 0,
  },
  {
    id: 1,
    link: "https://backend.partsg.com/storage/529/conversions/Tools-(1)-thumb.jpg",
    name: "Tools",
    model: "12135",
    price: "51,234",
    stock: 10,
  },
  {
    id: 2,
    link: "https://backend.partsg.com/storage/356/conversions/HEALTH-and-safety-(2)-thumb.jpg",
    name: "Health and Safety",
    model: "12135",
    price: "52,364",
    stock: 1,
  },
  {
    id: 3,
    link: "https://backend.partsg.com/storage/523/conversions/sub-catogries-thumb.jpg",
    name: "Filteration",
    model: "12135",
    price: "65,664",
    stock: 0,
  },
  {
    id: 4,
    link: "https://backend.partsg.com/storage/607/conversions/1-Filtration-thumb.jpg",
    name: "Category Test",
    model: "12135",
    price: "5,6664",
    stock: 0,
  },
  {
    id: 5,
    link: "https://backend.partsg.com/storage/524/conversions/Electrical-Equpment-(1)-thumb.jpg",
    name: "Electronics",
    model: "12135",
    price: "5,656,664",
    stock: 0,
  },
  {
    id: 6,
    link: "https://backend.partsg.com/storage/525/conversions/INSTRUMENTATION-thumb.jpg",
    name: "Instrumentation",
    model: "12135",
    price: "5,664",
    stock: 0,
  },
  {
    id: 7,
    link: "https://backend.partsg.com/storage/364/conversions/Compressor-thumb.jpg",
    name: "Compressor",
    model: "12135",
    price: "56,664",
    stock: 9,
  },
  {
    id: 8,
    link: "https://backend.partsg.com/storage/527/conversions/HEAVY-MACHINERY-&-EQUIPMENT-(2)-thumb.jpg",
    name: "Heavy Machinary & Equipment",
    model: "12135",
    price: "565,664",
    stock: 0,
  },
  {
    id: 9,
    link: "https://backend.partsg.com/storage/365/conversions/Couplings-thumb.jpg",
    name: "Coupling",
    model: "12135",
    price: "5,656,664",
  },
];
export const Cart = [
  {
    id: 0,
    link: "https://backend.partsg.com/storage/528/conversions/piplines-(1)-thumb.jpg",
    name: "Pipes",
    model: "12135",
    price: "5745",
    stock: 25,
    qty: 20,
  },
  {
    id: 1,
    link: "https://backend.partsg.com/storage/529/conversions/Tools-(1)-thumb.jpg",
    name: "Tools",
    model: "12135",
    price: "51234",
    stock: 10,
    qty: 2,
  },
  {
    id: 3,
    link: "https://backend.partsg.com/storage/523/conversions/sub-catogries-thumb.jpg",
    name: "Filteration",
    model: "12135",
    price: "65664",
    stock: 5,
    qty: 1,
  },
];
